### ISSUE TITLE
'Read-only file system' error when running example scripts

### ISSUE THREAD

**Issue by wpower12** [ctu-mrs/mrs_singularity#11]
I'm following the tutorial for using the singularity image. I can get everything installed (at least I see no error messages). However, when I go to run the example script called out in the tutorial, I get an open gazebo simulation, an open tmux session showing the various control panes, but no drone. 

I tried to do this step by step, instead of using the start.sh file, and I get the same issue. 

The minimum reproduction of this requires starting the mrs simulation with 'roslaunch mrs_simulation simulation.launch gui:=true', and then, in another window of the session, I run the command to spawn a drone 'waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 --enable-rangefinder"'. This commands output then tells me things have been launched. However, no drone appears in the gazebo simulation. Additionally, back in the window for the mrs_simulation node, I get the following error on repeat;

`[ERROR] [1674585030.281103, 1226.480000]: [DroneSpawner]: Error occured while spawning Gazebo model for uav1!
[INFO] [1674585030.282086, 1226.480000]: [DroneSpawner]: Spawning Gazebo model for uav1...
... logging to /home/bill/.ros/log/4be9fb68-9c12-11ed-ae20-a4ae111852f0/roslaunch-a3d-13120.log
Traceback (most recent call last):
  File "/opt/mrs/mrs_workspace/install/lib/mrs_simulation/jinja_gen.py", line 124, in <module>
    with open(filename_out, 'w') as f_out:
OSError: [Errno 30] Read-only file system: '/opt/mrs/mrs_workspace/install/share/mrs_simulation/models/mrs_robots_description/sdf/t650.sdf'`

I have a feeling this is due to some privilege issues pertaining to the setup/installation of singularity, but I can't be sure.

**Comment by gustavobraga98** [comment]
I am having the same problem. Did you find a solution?

**Comment by gustavobraga98** [comment]
Managed to overcome this issue by creating an overlay as instructed in the README and executing the wrapper.sh with sudo. It ran the simulation and failed while trying to load some plugins.

Steps to reproduce: 
`cd /opt/mrs/git/simulation/example_tmux_scripts/one_drone_gps`
`./start.sh`

Errors in the gazebo tab:

[Err] [Plugin.hh:212] Failed to load plugin /opt/mrs/mrs_workspace/install/lib/m
avlink_sitl_gazebo/plugins/libgazebo_motor_model.so: libphysics_msgs.so: cannot 
open shared object file: No such file or directory

[Err] [Plugin.hh:212] Failed to load plugin /opt/mrs/mrs_workspace/install/lib/m
avlink_sitl_gazebo/plugins/libgazebo_motor_model.so: libphysics_msgs.so: cannot 
open shared object file: No such file or directory

[Err] [Plugin.hh:212] Failed to load plugin /opt/mrs/mrs_workspace/install/lib/m
avlink_sitl_gazebo/plugins/libgazebo_motor_model.so: libphysics_msgs.so: cannot 
open shared object file: No such file or directory

[Err] [Plugin.hh:212] Failed to load plugin /opt/mrs/mrs_workspace/install
avlink_sitl_gazebo/plugins/libgazebo_motor_model.so: libphysics_msgs.so: cannot 
open shared object file: No such file or directory

[Err] [Plugin.hh:212] Failed to load plugin /opt/mrs/mrs_workspace/install/lib/m
avlink_sitl_gazebo/plugins/libgazebo_mavlink_interface.so: libphysics_msgs.so: c
annot open shared object file: No such file or directory

**Comment by gustavobraga98** [comment]
Just noticed that I can't use `roslaunch mrs_simulation simulation.launch gui:=true` when I execute wraper.sh as sudo

**Comment by klaxalk** [comment]
@gustavobraga98 you should not execute `wrapper.sh` with sudo. The only time when you should do that is when installing additional dependencies into the image or overlay. But you can not use the simulation while you do that.

**Comment by klaxalk** [comment]
@gustavobraga98, @wpower12 I will look into the issue, it looks like this might be related to our latest updates of the MRS system. In the meantime, please try building a singularity image of the last stable version. You can do that by substituting "latest" for "1.0.4" in the recipe file, e.g., in here: https://github.com/ctu-mrs/mrs_singularity/blob/a57676ace976cf1caf47e438779e2d4a952937cc/recipes/04_with_linux_setup_uav_modules/recipe.def#L3

**Comment by gustavobraga98** [comment]
@klaxalk Building the 1.0.4 version worked for me. Thanks!

**Comment by klaxalk** [comment]
@gustavobraga98, that's great! We think we fixed the problem on our end. The source docker images will be rebuilt by **tomorrow morning**. So if you want to upgrade, try the "latest" tag again tomorrow. Feel free to close the issue when you get it working. Thx!

**Comment by wpower12** [comment]
This change worked! After replacing the "latest" with "1.0.4", I now see all the panes running w.o error; gazebo loads, a drone spawns, and it moves to its way-point. 

Thank you for the response and suggestion!!
