### ISSUE TITLE
Whats the problem for running example ros uav?

### ISSUE THREAD

**Issue by zj0042** [ctu-mrs/mrs_singularity#12]
Hi all,
I have install singularity on Windows 10. I am trying to understand how the mrs running.
I entered commands like this: 
under this status [MRS Singularity] xx@xx: ~$ 
commands are : 
roslaunch mrs_simulation simulation.launch gui:=true
waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 --enable-rangefinder"
export UAV_NAME=uav1; waitForOdometry; roslaunch waypoint_flier waypoint_flier.launch

![mrs](https://user-images.githubusercontent.com/77756572/220520565-ef5233d9-fd31-4b65-b66a-0dfae6780195.png)

In Gazebo GUI, the drone did not move. I think there is something wrong.
Could anybody help with this? thank you so much

**Comment by klaxalk** [comment]
Hey, use the provided tmux sessions to start everything correctly. The commands are not meant to be issued manually in a single terminal.
