### ISSUE TITLE
Why does the second UAV not fly?

### ISSUE THREAD

**Issue by zj0042** [ctu-mrs/mrs_singularity#14]
I spawn two uavs and show their status in a window. they all worked a few days ago. But now the second one always didnt work. If I try to use rosservice call to spawn and command the uav to takeoff, the results were always wrong. 
Attached the screenshot and my config files. It really stopped my work to go ahead. Hope to sovle it as soon as possible.  
[error_MRS.zip](https://github.com/ctu-mrs/mrs_singularity/files/12491531/error_MRS.zip)

Could anybody help with this? Appreciate so much!

**Comment by petrlmat** [comment]
Hard to say what is happening just from the `mrs_status` screenshot and session and config files. Could you please provide the tmux logs? Mainly the `control` and `spawn` tabs.
