### ISSUE TITLE
git not working in MRS apptainer

### ISSUE THREAD

**Issue by saraybakker1** [ctu-mrs/mrs_singularity#19]
Hi! 

I am at step (5) of the Quick Start Guide (Linux), using Ubuntu22 and stable_from_docker in step 2.
Unfortunately, I am unable to do a git clone in the MRS Apptainer.  (git: command not found)
When starting it with ./wrapper.sh, I also get the error: "Error while mounting '/home/saray/.Xauthority', the path does not exist.". 

If I try to install git within the container, I have some issues with running sudo commands:
     "sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set"
and if I run the command without sudo, it complains about storage capacity:
     Not using locking for read only lock file /var/cache/apt/archives/lock
     E: You don't have enough free space in /var/cache/apt/archives/.
I am able to see the gazebo visual and everything generated in step 4. 
(Previously, I had some issues with normal docker where I had to set "priviliged=true", could this be an issue?)

Thanks already for your help :)

**Comment by klaxalk** [comment]
Hey, thanks, we missed that. I have added `git` into the recipes.

I would recommend you to `git pull` master and regenerate the singularity image. Alternatively, you can `git clone` the examples from outside of the container, where you might have git installed.

Finally-alternatively, you can try creating an overlay (https://github.com/ctu-mrs/mrs_apptainer?tab=readme-ov-file#creating-persistent-overlay-preferred), installing git inside the overlay and later embedding it in the image you already have. This will probably be faster than generating a new image.

**Comment by saraybakker1** [comment]
thanks for the help, it works
