### ISSUE TITLE
Getting root privileges in singularity container

### ISSUE THREAD

**Issue by yhdurkaya** [ctu-mrs/mrs_singularity#3]
Hello folks,
I have built and run the simulation and currently everything seems to work. However, when I tried to change the one_drone_gps/session.yml to use a different world file, I can't change because of permission.

To fix this I switch "KEEP_ROOT_PRIVS" to true in wrapper.sh but it didn't solve the problem. When I run `vim session.yml` to change the world file part as guided in https://ctu-mrs.github.io/docs/simulation/custom_world.html I ran across a different kind of error.

![sss](https://user-images.githubusercontent.com/47098320/169030464-d474c6f7-e3d1-4414-bbbd-8e59c9c12f00.png)

I am guessing this is about UID but my UID in the container is 0, as it must be. 

I am not sure how to solve this error.

**Comment by klaxalk** [comment]
Hey, you can get root privileges by running the container by either of the two following:
a) an active overlay and running the wrapper with `sudo`,
b) a sandbox container and running it with `FAKE_ROOT=true`
then you can change the file or install other dependencies.

However, for your use case, I just recommend copying the session to a location that is not in the image, so some user-mounted directory from your host machine. E.g., something in the user_ros_workspace.

**Comment by yhdurkaya** [comment]
I tried to copy the one_drone_gps_mrs_city example to user_ros_workspace and changed it there. Thankfully, it worked and thanks for your help.
I do have another question though. 

I changed the drone into an f550 and sensor to the realsense-front-pitched and it has some problems. The drone is created and I can see rostopics and all that but I can't move the drone because it lacks some information about odometry and control.

I am putting here all the screenshots from tmux terminals.
Gazebo
![gazebo](https://user-images.githubusercontent.com/47098320/169848688-acbfa6c6-7f13-40a5-a82e-a5474401c2f8.png)
Status
![status](https://user-images.githubusercontent.com/47098320/169848732-b602acc3-ce68-4c65-a74d-012c50d62cba.png)
Control
![control](https://user-images.githubusercontent.com/47098320/169848757-a23a3f26-07af-4dc0-86ac-fda8a7c12eb7.png)
Rviz
![rviz](https://user-images.githubusercontent.com/47098320/169848800-782d96ac-5539-4551-a655-169abfff503c.png)
Takeoff
![takeoff](https://user-images.githubusercontent.com/47098320/169848838-68772eee-e48e-4ba2-a2cd-2baf7c606ad7.png)

Is this about the frame? If so, I can change it into something usable with front pitched realsense sensor.
Just another point, when I try to takeoff using the menu on the Status page, it errors as "Service call failed: can not takeoff, missing odometry."

**Comment by yhdurkaya** [comment]
For anyone that might encounter with the same problem, it is about range finder. I guess it is necessary for a drone to takeoff. I thought GPS data is enough but I am wrong. Do not remove the rangefinder to put a new sensor, just add a new one and use both.

Thanks for all your help @klaxalk, I am closing this issues since everything seems to be solved. See you in a couple of days for a new issue:)

**Comment by klaxalk** [comment]
@yhdurkaya you were right :-), the default "GPS" estimator profile ([link](https://github.com/ctu-mrs/mrs_uav_odometry/blob/master/config/simulation/gps.yaml)) has the "HEIGHT" estimator active. So it requires the Garmin rangefinder to take off.
