### ISSUE TITLE
Build script throws errors

### ISSUE THREAD

**Issue by yhdurkaya** [ctu-mrs/mrs_singularity#9]
Hello folks,
I am trying to install the singularity container following your instructions. When following Quick Start Guide for Linux, 
Step 1 is OK. 
Step 2 is optional so I dont install Docker. 
In the 3rd step when building recipe04, it throws this error below.

![mrs](https://user-images.githubusercontent.com/47098320/196895352-5de28b76-a43f-4d32-9fce-b554049c172b.png)

How can I handle this error?

**Comment by klaxalk** [comment]
Thanks, I will look into it.

**Comment by klaxalk** [comment]
This looks like an error in unpacking/downloading the underlying docker image from the docker hub. Could you try running `build.sh` again? Do you have enough (at least 20GB) of free HDD space? In the meantime, you can download a fresh singularity I just built from here: https://nasmrs.felk.cvut.cz/index.php/s/MI7B1enHfQAWumW, then place it in the `images` subfolder of the mrs_singularity repository.

**Comment by yhdurkaya** [comment]
I have enough space, much more than 20GB.

The link you provided is working as expected. Thanks for your help.
